name: Look at different options
on:
  workflow_dispatch:
    inputs:
      environment_option:
        description: Select an option
        required: true
        default: all
      environment_type:
        description: Select the environment name to run the actions on
        required: true
        type: choice
        options:
          - staging
          - production
          - staging and production
        default: staging and production

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          environment_options=$(jq -r '.environment[]' config.json)
          all_types=("staging" "production" "staging and production")
          excluded=$(jq -c '.excluded_environments[]' config.json)

          matrix="{\"include\": ["
          for type in "${all_types[@]}"; do
            for option in $environment_options; do
              if ! echo "$excluded" | grep -q "{\"environment-type\": \"$type\", \"environment-name\": \"$option\"}"; then
                matrix+="{\"environment-type\": \"$type\", \"environment-name\": \"$option\"},"
              fi
            done
          done
          matrix="${matrix%,}]}" # Remove trailing comma and close bracket
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-code:
    name: See which option was selected
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Output Matrix
        run: |
          echo "Matrix Combinations:"
          cat <<EOF | jq
          ${{ fromJson(needs.set-matrix.outputs.matrix) }}
          EOF
      - name: Show which option was selected
        run: echo "The option selected was ${{ github.event.inputs.environment_option }} in ${{ github.event.inputs.environment_type }}"
