name: Look at different options
on:
  workflow_dispatch:
    inputs:
      environment_option:
        type: choice
        description: Select an option
        options:
          - option1
          - option2
          - option3
          - option4
          - all
        default: all

jobs:
  run-code:
    name: See which option was selected
    runs-on: ubuntu-latest
    steps:
      - name: Show which option was selected
        run: echo "The option selected was ${{ github.event.inputs.environment_option }}"