name: Look at different options
on:
  workflow_dispatch:
    inputs:
      environment_option:
        description: Select an option
        required: true
        default: all

jobs:
  run-code:
    name: See which option was selected
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read options from config file
        id: options
        run: |
          OPTIONS=$(jq -r '.options | join(",")' config.json)
          echo "OPTIONS=$OPTIONS" >> $GITHUB_ENV
        shell: bash
      - name: Validate input against config
        run: |
          IFS=',' read -ra valid_options <<< "$OPTIONS"
          for i in "${valid_options[@]}"; do
            if [[ "${{ github.event.inputs.environment_option }}" == "$i" ]]; then
              echo "Valid option selected"
              exit 0
            fi
          done
          echo "Invalid option selected"
          exit 1
      - name: Show which option was selected
        run: echo "The option selected was ${{ github.event.inputs.environment_option }}"